### ISSUE TITLE
no mean, std_dev for student_t

### ISSUE THREAD

**Issue by hiok2000** [ankane/dist.h#1]
shuold agree with python scipy

  student_t_ppf(p, df)
only euqal to
  import scipy.stats as stats
  stats.t.ppf(p, loc=0.0, scale=1.0, df=df)
should like:
  student_t_ppf(p, df, mean, std_dev)
  stats.t.ppf(p, loc=mean, scale=std_dev, df=df)

**Comment by hiok2000** [comment]
> shuold agree with python scipy
> 
> student_t_ppf(p, df) only euqal to import scipy.stats as stats stats.t.ppf(p, loc=0.0, scale=1.0, df=df) should like: student_t_ppf(p, df, mean, std_dev) stats.t.ppf(p, loc=mean, scale=std_dev, df=df)

change to:
student_t_ppf(p, df, mean, std_dev){
...
return mean + std_dev * sign * sqrt(n * y);  // only here
}

work!

**Comment by hiok2000** [comment]
OK... all returns should add  mean + std_dev *...

I only verify stats.t.ppf(p, loc=mean, scale=std_dev, df=3) when df=3

**Comment by ankane** [comment]
Hey @hiok2000, thanks for the suggestion. Since the transformation is pretty straightforward, I don't think extra parameters are needed.
